// date sorted from backend
// add time, price, ticket

export const listData = [
  {
    id: 1,
    tag: 'math',
    tagId: '0',
    topic: 'Calculus 2',
    location: "ECC 801",
    tutor: 'Kanat Krub',
    amount: "3",
    full :"15",
    date: '03/02/20',
    startTime: '09:00',
    stopTime: '12:00',
    price: '120',
    ticket: '',
    img: "",
  },
  {
    id: 2,
    tag: 'sci',
    tagId: '1',
    topic: 'Movement',
    location: "Hardware Lab",
    tutor: 'Kru P Aum',
    amount: "4",
    full :"10",
    date: '05/02/20',
    startTime: '11:00',
    stopTime: '12:30',
    price: '200',
    ticket: '',
    img: "",
  },
  {
    id: 3,
    tag: 'thai',
    tagId: '2',
    topic: 'Wan na ka dee',
    location: "ISAG",
    tutor: 'Kru P lukkade',
    amount: "10",
    full :"10",
    date: '05/02/20',
    startTime: '11:30',
    stopTime: '14:00',
    price: '50',
    ticket: '',
    img: "",
  },
  {
    id: 4,
    tag: 'eng',
    tagId: '3',
    topic: 'Toeic300',
    location: "HCRL",
    tutor: 'Somsri Jah',
    amount: "5",
    full :"10",
    date: '10/02/20',
    startTime: '09:30',
    stopTime: '11:00',
    price: '1000',
    ticket: '',
    img: "",
  },
  {
    id: 5,
    tag: 'social',
    tagId: '4',
    topic: 'Na tee pol la mueng',
    location: "E12 501",
    tutor: 'Kru wandee',
    amount: "15",
    full :"20",
    date: '15/02/20',
    startTime: '14:00',
    stopTime: '17:00',
    price: '25',
    ticket: '',
    img: "",
  },
  {
    id: 6,
    tag: 'math',
    tagId: '0',
    topic: 'Number Theory',
    location: "D 403",
    tutor: 'P Ae',
    amount: "3",
    full :"5",
    date: '17/02/20',
    startTime: '18:00',
    stopTime: '20:00',
    price: '250',
    ticket: '',
    img: "",
  },
  {
    id: 7,
    tag: 'sci',
    tagId: '1',
    topic: 'Kingdom',
    location: "HM 305",
    tutor: 'P Yuth',
    amount: "32",
    full :"45",
    date: '20/02/20',
    startTime: '13:00',
    stopTime: '16:30',
    price: '300',
    ticket: '',
    img: "",
  },
  {
    id: 8,
    tag: 'social',
    tagId: '3',
    topic: 'Coup by P Yuth',
    location: "ECC 811",
    tutor: 'P yuth',
    amount: "18",
    full :"25",
    date: '22/02/20',
    startTime: '17:00',
    stopTime: '19:30',
    price: '150',
    ticket: '',
    img: "",
  },
];
