// date sorted from backend
// add time, price, ticket

export const listData = [
  {
    id: 1,
    tag: 'math',
    tagId: '0',
    topic: 'Calculus 2',
    location: "GOOGLE",
    tutor: 'Kanat Krub',
    amount: "1",
    full :"10",
    date: '03/02/20',
    time: '',
    price: '120',
    ticket: '',
    img: "",
  },
  {
    id: 2,
    tag: 'sci',
    tagId: '1',
    topic: 'Movement',
    location: "GOOGLE",
    tutor: 'Kru P Aum',
    amount: "1",
    full :"10",
    date: '05/02/20',
    time: '',
    price: '200',
    ticket: '',
    img: "",
  },
  {
    id: 3,
    tag: 'thai',
    tagId: '2',
    topic: 'Wan na ka dee',
    location: "GOOGLE",
    tutor: 'Kru P lukkade',
    amount: "1",
    full :"10",
    date: '05/02/20',
    time: '',
    price: '50',
    ticket: '',
    img: "",
  },
  {
    id: 4,
    tag: 'eng',
    tagId: '3',
    topic: 'Toeic300',
    location: "GOOGLE",
    tutor: 'Somsri Jah',
    amount: "1",
    full :"10",
    date: '10/02/20',
    time: '',
    price: '1000',
    ticket: '',
    img: "",
  },
  {
    id: 5,
    tag: 'social',
    tagId: '4',
    topic: 'Na tee pol la mueng',
    location: "GOOGLE",
    tutor: 'Kru wandee',
    amount: "1",
    full :"10",
    date: '15/02/20',
    time: '',
    price: '25',
    ticket: '',
    img: "",
  },
  {
    id: 6,
    tag: 'math',
    tagId: '0',
    topic: 'Number Theory',
    location: "GOOGLE",
    tutor: 'P Ae',
    amount: "1",
    full :"10",
    date: '17/02/20',
    time: '',
    price: '250',
    ticket: '',
    img: "",
  },
  {
    id: 7,
    tag: 'sci',
    tagId: '1',
    topic: 'Kingdom',
    location: "GOOGLE",
    tutor: 'P Yuth',
    amount: "1",
    full :"10",
    date: '20/02/20',
    time: '',
    price: '300',
    ticket: '',
    img: "",
  },
  {
    id: 8,
    tag: 'social',
    tagId: '3',
    topic: 'Coup by P Yuth',
    location: "GOOGLE",
    tutor: 'P yuth',
    amount: "1",
    full :"10",
    date: '22/02/20',
    time: '',
    price: '150',
    ticket: '',
    img: "",
  },
];
