// add in 13-Mar-20
// add name list of people joined tue.

export const myPostingData = [
  {
    id: 1,
    tag: 'Science',
    tagId: '1',
    topic: 'Work and Energy',
    location: "ECC 811",
    tutor: 'Kru P Ae',
    amount: "6",
    full :"20",
    date: '13/03/20',
    startTime: '09:30',
    stopTime: '12:00',
    price: '200',
    img: "",
    participant: [
      {
        id: 11,
        name: 'Werawit Sirakunwat',
        ticket: '000001',
        isRedeem: false,
      },
      {
        id: 19,
        name: 'Natthapol Lekkuna',
        ticket: '000002',
        isRedeem: false,
      },
      {
        id: 21,
        name: 'Nawapon Khampraw',
        ticket: '000003',
        isRedeem: false,
      },
      {
        id: 29,
        name: 'Tanachot Humpra',
        ticket: '000004',
        isRedeem: false,
      },
      {
        id: 31,
        name: 'Korawith Suwanarat',
        ticket: '000005',
        isRedeem: false,
      },
      {
        id: 35,
        name: 'Kongkeat Sangrujee',
        ticket: '000006',
        isRedeem: false,
      },
    ],
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    id: 2,
    tag: 'English',
    tagId: '3',
    topic: 'CUTEP 800++',
    location: "E12 502",
    tutor: 'Kru P Aum',
    amount: "12",
    full :"30",
    date: '15/03/20',
    startTime: '13:00',
    stopTime: '16:30',
    price: '500',
    img: "",
    participant: [
      {
        id: 11,
        name: 'Werawit Sirakunwat',
        ticket: '000007',
        isRedeem: false,
      },
      {
        id: 19,
        name: 'Natthapol Lekkuna',
        ticket: '000008',
        isRedeem: false,
      },
      {
        id: 21,
        name: 'Nawapon Khampraw',
        ticket: '000009',
        isRedeem: false,
      },
      {
        id: 29,
        name: 'Tanachot Humprae',
        ticket: '000010',
        isRedeem: false,
      },
      {
        id: 31,
        name: 'Korawith Suwanarat',
        ticket: '000011',
        isRedeem: false,
      },
      {
        id: 35,
        name: 'Kongkeat Sangrujee',
        ticket: '000012',
        isRedeem: false,
      },
      {
        id: 41,
        name: 'Kittichai Wilaipong',
        ticket: '000013',
        isRedeem: false,
      },
      {
        id: 42,
        name: 'Thanapon Purahong',
        ticket: '000014',
        isRedeem: false,
      },
      {
        id: 44,
        name: 'Tanachit Chaingsai',
        ticket: '000015',
        isRedeem: false,
      },
      {
        id: 52,
        name: 'Pacharapol Chaiyakul',
        ticket: '000016',
        isRedeem: false,
      },
      {
        id: 75,
        name: 'Padtaraporn Kwanyuen',
        ticket: '000017',
        isRedeem: false,
      },
      {
        id: 80,
        name: 'Supakit Pukasorn',
        ticket: '000018',
        isRedeem: false,
      },

    ],
    description: '',
  },
];
